#!/usr/bin/env bash
# This script will be used to install dependencies for all the Gitzer applications

# directory path of django development server
backend_folder="gitzer"
# directory path of nuxt development server
frontend_folder="gitzer-frontend"
# directory path of documentation development server
documentation_folder="gitzer-docs"


# change to the project folder
cd "/home/vagrant/Gitzer"
# install the dependencies for the frontend application
cd "$frontend_folder" && yarn

# change to the project folder
cd "/home/vagrant/Gitzer"
# install the dependencies for the documentation application
cd "$documentation_folder" && yarn

# change to the project folder
cd "/home/vagrant/Gitzer"
# install the dependencies for the django application
cd "$backend_folder"
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
curl -sSL https://raw.githubusercontent.com/IgnisDa/Gitzer/main/get-gitzer.py | python3 -
source $HOME/.poetry/env
poetry config virtualenvs.in-project "true"
poetry install
