#!/usr/bin/env bash
# This script will be used to install dependencies for all the Gitzer applications

# setup the git identities
git config --global user.name "IgnisDa"
git config --global user.email "ignisda2001@gmail.com"

# directory path of django development server
backend_folder="gitzer"
# directory path of nuxt development server
frontend_folder="gitzer-frontend"
# directory path of documentation development server
documentation_folder="gitzer-docs"

# remove the default fish shell prompt
set fish_greeting

# replace the default file content viewer (cat) with bat
sudo ln -s /usr/bin/batcat /usr/bin/bat
# load all my system configs
rm -rf $HOME/.config
git clone https://github.com/IgnisDa/linux-configs.git $HOME/.config

# use the starship prompt
curl -fsSL https://starship.rs/install.sh > /tmp/install.sh
chmod +x /tmp/install.sh
/tmp/install.sh --force

# load the custom scripts and make only files which contain `~ADD_SCRIPT~` in them
# executable
CUSTOM_SCRIPTS_DIR="$HOME/custom-scripts"
git clone https://github.com/IgnisDa/custom-scripts.git $CUSTOM_SCRIPTS_DIR
for file in "$CUSTOM_SCRIPTS_DIR"/*; do
    if grep -Fq "~ADD_SCRIPT~" "$file"; then
        chmod +x "$file"
    fi
done

# set the default interactive shell as fish
rm -rf "$HOME/.bashrc"
ln -s "$HOME/.config/.bashrc" "$HOME/.bashrc"

# change to the project folder
cd "/home/vagrant/Gitzer"
# install the dependencies for the frontend application
cd "$frontend_folder"
eval "$CUSTOM_SCRIPTS_DIR/setup"

# change to the project folder
cd "/home/vagrant/Gitzer"
# install the dependencies for the documentation application
cd "$documentation_folder"
eval "$CUSTOM_SCRIPTS_DIR/setup"

# change to the project folder
cd "/home/vagrant/Gitzer"
# install the dependencies for the django application
cd "$backend_folder"
curl -sSL https://raw.githubusercontent.com/IgnisDa/Gitzer/main/get-gitzer.py | python3 -
source $HOME/.poetry/env
poetry config virtualenvs.in-project "true"
eval "$CUSTOM_SCRIPTS_DIR/setup"
