# Generated by Django 3.1.5 on 2021-01-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='The absolute path to the local git repository.', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='The date and time this repository was logged on.')),
            ],
        ),
    ]
