#!/usr/bin/env bash

backend_folder="gitzer"
frontend_folder="gitzer-frontend"
rm -rf "build/"
mkdir "build/"
cd ~/Gitzer
cd "$frontend_folder" && yarn && yarn generate
cd ~/Gitzer
rsync -av --progress "$frontend_folder/dist/" "build/"

cd ~/Gitzer
rsync -av --progress "$backend_folder/" "build/" \
    --exclude "tests" --exclude ".venv" \
    --exclude "poetry.lock" \
    --exclude ".flake8" --exclude "db.sqlite3" \
    --exclude "pyproject.toml" --exclude "pytest.ini"
cd "build/"
python3 -m venv _vendor
source _vendor/bin/activate
pip3 install -r requirements.txt
cd ~/Gitzer
cp "tools/simple-server.py" "build/simple-server.py"

tar cvfz gitzer.tar.gz build/
